### ISSUE TITLE
The Game Engine needs to cycle through VMs

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#17]
Its important that the Game Engine only spend a few seconds processing one VM before moving onto the next.  When the Game Engine stops a VM it should maintain all the state variables so it can pick up where it left off the next time it returns to that VM.

**Comment by crodnun** [comment]
Initial support for this feature is in place. The basics are simple, Richard added at this version a callback that each VM can use to call our C codes to check if has to continue or not, our callback answers depending on the number of seconds elapsed since we started running commands, this way we limit the time each VM uses, or at least I hope so, when not done yet, we store provisional output and do not send any email, till finished. The time we use to measure this, is configurable at game-engine.conf, as follows:
# Max time a VM can run commands per cycle
MAX_CYCLE_SECONDS = "5"
If you have some loops examples or heavy scripts I could test it, to confirm that it works as intended.

**Comment by darozak** [comment]
You can try this simple loop to test the process:
<script> : looping begin 1 - dup dup . 0 = until ; </script>

After defining looping with the above statement you can make the drone count down from 10 by sending the following script:
<script> 10 looping </script>

The higher the number, the longer it will take for the drone to count down.

Using a number less than zero should generate an infinite loop that requires the <abort> command to stop.
<script> -10 looping </script>

If other drones still respond to commands while the first drone is in the infinite loop then you also know that the VM cycling is working.

Please test and see if it works.

**Comment by crodnun** [comment]
Hi Dave,
Richard has posted his answer regarding the loop we are using. Seems incorrect, see his answer here
https://github.com/howerj/embed/issues/4

**Comment by darozak** [comment]
Now that the GE successfully cycles through the VMs we can close out this issue.  Thanks!!
