### ISSUE TITLE
Event tables must also track the new_quantity of the added resource

### ISSUE THREAD

**Issue by darozak** [Darwin-River/Ex-Machinis#38]
In addition to keeping a running tally of the new_cargo value, events that add or subtract materials from the cargo hold must also keep a running tally of the affected resource in the new_quantity field.  Without doing this we lose track of how many iron or carbon ores are in the spacecraft's cargo hold.  Right now this value is zero for all events.

**Comment by crodnun** [comment]
Fixed this bug, check if this is what you expect, now we should have sequences like this:

| 39 |          2 |     36 |      1 |       1 |     1 |        1 |         0 |      0 |           -4 |           0 |            0 |                0 |        33 | 2019-09-22 10:25:07 |
| 40 |          1 |     37 |      1 |       1 |     1 |        1 |         0 |      0 |           10 |           0 |            0 |                0 |        43 | 2019-09-22 10:25:37 |
| 41 |          1 |     38 |      1 |      -3 |     1 |        1 |         0 |      0 |           20 |           0 |            0 |                0 |        63 | 2019-09-22 10:25:57 |
| 42 |          2 |     39 |      1 |       1 |     1 |        1 |         0 |      0 |          -10 |           0 |            0 |                0 |        33 | 2019-09-22 10:26:07 |
| 43 |          1 |     40 |      1 |      -3 |     1 |        1 |         0 |      0 |           20 |           0 |            0 |                0 |        53 | 2019-09-22 10:26:22 |


Due to this bug, the new_quantity was set always to 0 in DB.

**Comment by darozak** [comment]
Although the new_quantities field might be negative for events that have not yet been processed by the Event Engine (indicating a scheduled depletion event), they should always be >= 0 after being processed by the Event Engine.  This is because the new_quantities field goes from representing a net change before the event is processed to representing a total amount of an item after the event is processed.  If the event attempts to remove more of the resource than is available in the cargo hold (resulting in a negative value) the event will not take place and the corresponding action will be aborted.

**Comment by crodnun** [comment]
I do not understand this part, anyways I have added a minor change to see if this is the expected behaviour.
This way, when an event is successfully processed (outcome = 1), the final values for new_quantity and new_cargo are the same, isn't it? Let me know if I am correct

**Comment by darozak** [comment]
Apologies for not doing a good job in describing it.  Unfortunately, the mod and your interpretation, which you describe above, are not correct.    Let me see if I can do a better job describing the difference between these two variables.

The new_cargo field contains the total amount of ALL resources held in the cargo hold following the event.  In our current test environment this would include the total amount of both iron and carbon ore in the cargo hold.

The new_quantity field only totals the amount of the resource affected by that particular event.  So if the event deals with iron ore, the new_quantity will be the amount of iron ore in the cargo hold following completion of the event.  The new_quantity value will be less than the new_cargo value if other resources, such as carbon ore, are also being stored in the ship's hold.

**Comment by crodnun** [comment]
Ok, will try to update the system to take this into account. Today I gave it a hit but still failing

**Comment by crodnun** [comment]
Implemented new changes to deal with this, to be tested.

Now we keep track of the amount of the current resources (at new_quantity field) and at new_cargo we keep the total cargo (for all the resources).

**Comment by darozak** [comment]
Working perfectly!  Thanks.
